id: io.github.sanny32.omodscan
branch: stable
runtime: org.kde.Sdk
runtime-version: "6.9"
sdk: org.kde.Sdk
command: omodscan
finish-args:
  - "--socket=wayland"
  - "--socket=fallback-x11"
  - "--socket=cups"
  - "--device=all"
  - "--share=network"
  - "--filesystem=home"
  - "--system-talk-name=org.freedesktop.UDisks2"
cleanup:
  - /include
  - /lib/cmake
  - /lib/libexec
  - /lib/metatypes
  - /lib/pkgconfig
  - /lib/sbom
  - /lib/systemd
  - /bin/canbusutil
  - /mkspecs
  - /modules
  - '*.a'

modules:
  - name: qt6-serialport
    buildsystem: cmake
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
    sources:
      - type: archive
        url: https://mirrors.20i.com/pub/qt.io/archive/qt/6.9/6.9.3/submodules/qtserialport-everywhere-src-6.9.3.tar.xz
        sha256: 4b18ec030ff2644698c3f5c776894d8ffe5d3174c964d9bd8668429c943e8298

  - name: qt6-serialbus
    buildsystem: cmake
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_FEATURE_socketcan=OFF
    sources:
      - type: archive
        url: https://mirrors.20i.com/pub/qt.io/archive/qt/6.9/6.9.3/submodules/qtserialbus-everywhere-src-6.9.3.tar.xz
        sha256: 0a8139da071afcb768b9d115f514a3e5783312530b2be69e3ee42b301d775bcf

  - name: omodscan
    builddir: true
    buildsystem: simple
    build-commands:
        - cmake -DCMAKE_BUILD_TYPE=Release -B ../build
        - cmake --build ../build -- -j$(nproc)
    post-install:
      - install -D ../build/omodscan /app/bin/omodscan
      - install -Dm644 ../../usr/share/icons/hicolor/128x128/omodscan.png -t /app/share/icons/hicolor/128x128/apps/io.github.sanny32.omodscan.png
      - install -Dm644 ../../usr/share/applications/omodscan.desktop -t /app/share/applications/io.github.sanny32.omodscan.desktop
      - install -Dm644 ../../usr/share/metainfo/omodscan.metainfo.xml -t /app/share/metainfo/io.github.sanny32.omodscan.metainfo.xml
    subdir: src
    sources:
      - type: git
        url: https://github.com/sanny32/OpenModScan.git
        branch: main
      - type: file
        path: ../../linux/usr/share/icons/hicolor/128x128/omodscan.png
      - type: file
        path: ../../linux/usr/share/applications/omodscan.desktop
      - type: file
        path: ../../linux/usr/share/metainfo/omodscan.metainfo.xml
