id: io.github.sanny32.omodscan
branch: stable
runtime: org.kde.Sdk
runtime-version: "6.9"
sdk: org.kde.Sdk
command: omodscan
finish-args:
  - "--socket=wayland"
  - "--socket=fallback-x11"
  - "--socket=cups"
  - "--device=all"
  - "--share=network"
  - "--filesystem=home"
  - "--system-talk-name=org.freedesktop.UDisks2"
cleanup:
  - /include
  - /lib/cmake
  - /lib/libexec
  - /lib/metatypes
  - /lib/pkgconfig
  - /lib/sbom
  - /lib/systemd
  - /bin/canbusutil
  - /mkspecs
  - /modules
  - '*.a'

modules:
  - name: qt6-serialport
    buildsystem: cmake
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
    sources:
      - type: archive
        url: https://mirrors.20i.com/pub/qt.io/archive/qt/6.9/6.9.3/submodules/qtserialport-everywhere-src-6.9.3.tar.xz
        sha256: 4b18ec030ff2644698c3f5c776894d8ffe5d3174c964d9bd8668429c943e8298

  - name: qt6-serialbus
    buildsystem: cmake
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_FEATURE_socketcan=OFF
    sources:
      - type: archive
        url: https://mirrors.20i.com/pub/qt.io/archive/qt/6.9/6.9.3/submodules/qtserialbus-everywhere-src-6.9.3.tar.xz
        sha256: 0a8139da071afcb768b9d115f514a3e5783312530b2be69e3ee42b301d775bcf

  - name: omodscan
    builddir: true
    buildsystem: simple
    build-commands:
      - cmake -DCMAKE_BUILD_TYPE=Release -B ../build
      - cmake --build ../build -- -j$(nproc)

    post-install:
      - |
        sed -e "s|@APP_EXEC@|/app/bin/omodscan|g" \
            -e "s|@APP_ICON@|io.github.sanny32.omodscan|g" \
            omodscan.desktop.in > /app/share/applications/io.github.sanny32.omodscan.desktop
  
      - |
        REF_NAME=$(git -C src rev-parse --abbrev-ref HEAD)
        sed -e "s|@REF_NAME@|$REF_NAME|g" \
            -e "s|@COMPONENT_ID@|io.github.sanny32.omodscan|g" \
            -e "s|@APP_ICON@|io.github.sanny32.omodscan|g" \
            omodscan.metainfo.xml.in > /app/share/metainfo/io.github.sanny32.omodscan.metainfo.xml

      - install -D ../build/omodscan /app/bin/omodscan
      
      - install -Dm644 omodscan-128x128.png  -t   /app/share/icons/hicolor/128x128/apps/io.github.sanny32.omodscan.png
      - install -Dm644 omodscan-64x64.png    -t   /app/share/icons/hicolor/64x64/apps/io.github.sanny32.omodscan.png
      - install -Dm644 omodscan-32x32.png    -t   /app/share/icons/hicolor/32x32/apps/io.github.sanny32.omodscan.png
      - install -Dm644 omodscan-16x16.png    -t   /app/share/icons/hicolor/16x16/apps/io.github.sanny32.omodscan.png

    subdir: src
    sources:
      - type: git
        url: https://github.com/sanny32/OpenModScan.git
        branch: main
      - type: file
        path: ../usr/share/icons/hicolor/128x128/apps/omodscan.png
        dest: omodscan-128x128.png
      - type: file
        path: ../usr/share/icons/hicolor/64x64/apps/omodscan.png
        dest: omodscan-64x64.png
      - type: file
        path: ../usr/share/icons/hicolor/32x32/apps/omodscan.png
        dest: omodscan-32x32.png
      - type: file
        path: ../usr/share/icons/hicolor/16x16/apps/omodscan.png
        dest: omodscan-16x16.png
      - type: file
        path: ../usr/share/applications/omodscan.desktop.in
        dest: omodscan.desktop.in
      - type: file
        path: ../usr/share/metainfo/omodscan.metainfo.xml.in
        dest: omodscan.metainfo.xml.in
