#!/bin/bash
# This `DEBIAN/postrm` script is run post-remove

if [ -f /etc/udev/rules.d/99-omodscan.rules ]; then
    rm -f /etc/udev/rules.d/99-omodscan.rules
    udevadm trigger
fi

xdg-desktop-menu forceupdate
rm -f /usr/bin/omodscan
